#!/usr/bin/env bash

west flash --runner openocd

# /opt/west/zephyr-sdk-1.0.1/hosttools/sysroots/x86_64-pokysdk-linux/usr/bin/openocd \
# -s /opt/west/zephyr/boards/st/nucleo_f411re/support \
# -s /opt/west/zephyr-sdk-1.0.1/hosttools/sysroots/x86_64-pokysdk-linux/usr/share/openocd/scripts \
# -f /opt/west/zephyr/boards/st/nucleo_f411re/support/openocd.cfg \
# '-c init' \
# '-c targets' \
# -c 'reset init' \
# -c 'flash write_image \
# erase \
# /workspaces/hello_world/build/zephyr/zephyr.hex' \
# -c 'reset run' \
# -c shutdown